changelog:
  categories:
    - title: Updates
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
        authors:
          - dependabot

    - title: Dependencies
      labels:
        - dependencies
