name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build
      - run: ./.github/workflows/verify_dist_index.js.sh
        shell: bash
      - uses: ./
        with:
          token: ${{ secrets.TYPETALK_TOKEN }}
          topic_id: ${{ secrets.TYPETALK_TOPIC_ID }}
          message: "Build completed successfully"

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run test
